"""Predefined discharge barrier catalog for California acute care hospitals."""

BARRIER_CATALOG = {
    "pt_eval_pending": {
        "label": "PT Evaluation Pending",
        "category": "clinical",
        "default_sla_hours": 24,
        "description": "Physical therapy evaluation not yet completed",
        "auto_detect_keywords": ["PT evaluation", "physical therapy eval", "PT not completed",
                                  "PT pending", "physical therapy pending"],
    },
    "ot_eval_pending": {
        "label": "OT Evaluation Pending",
        "category": "clinical",
        "default_sla_hours": 24,
        "description": "Occupational therapy evaluation not yet completed",
        "auto_detect_keywords": ["OT evaluation", "occupational therapy eval", "OT pending"],
    },
    "st_eval_pending": {
        "label": "Speech Therapy Evaluation Pending",
        "category": "clinical",
        "default_sla_hours": 48,
        "description": "Speech/language pathology evaluation not yet completed",
        "auto_detect_keywords": ["ST evaluation", "speech therapy eval", "SLP pending",
                                  "swallowing evaluation"],
    },
    "wound_care_unresolved": {
        "label": "Wound Care Unresolved",
        "category": "clinical",
        "default_sla_hours": 24,
        "description": "Open wound or wound care order not yet completed before discharge",
        "auto_detect_keywords": ["wound care", "wound not healed", "wound management pending",
                                  "dressing change needed"],
    },
    "labs_pending": {
        "label": "Pending Lab Results",
        "category": "clinical",
        "default_sla_hours": 12,
        "description": "Critical lab results outstanding that may affect discharge decision",
        "auto_detect_keywords": ["pending labs", "awaiting lab", "lab results pending",
                                  "INR not checked", "culture pending"],
    },
    "med_reconciliation_incomplete": {
        "label": "Medication Reconciliation Incomplete",
        "category": "clinical",
        "default_sla_hours": 12,
        "description": "Medication list not fully reconciled for discharge",
        "auto_detect_keywords": ["medication reconciliation incomplete", "med rec pending",
                                  "discharge meds not reconciled"],
    },
    "snf_auth_pending": {
        "label": "SNF Prior Authorization Pending",
        "category": "authorization",
        "default_sla_hours": 48,
        "description": "SNF placement authorization not yet obtained from payer",
        "auto_detect_keywords": ["SNF authorization", "SNF auth pending", "prior auth SNF",
                                  "SNF prior auth", "skilled nursing auth", "Medi-Cal SNF auth",
                                  "Medicare SNF authorization"],
    },
    "home_health_auth_pending": {
        "label": "Home Health Authorization Pending",
        "category": "authorization",
        "default_sla_hours": 24,
        "description": "Home health services prior authorization not obtained",
        "auto_detect_keywords": ["home health auth", "HHA authorization", "home health prior auth"],
    },
    "dme_auth_pending": {
        "label": "DME Authorization Pending",
        "category": "authorization",
        "default_sla_hours": 24,
        "description": "Durable medical equipment order or authorization not completed",
        "auto_detect_keywords": ["DME authorization", "equipment auth", "durable medical equipment pending",
                                  "wheelchair auth", "hospital bed auth", "oxygen auth"],
    },
    "insurance_eligibility_unverified": {
        "label": "Insurance Eligibility Unverified",
        "category": "authorization",
        "default_sla_hours": 8,
        "description": "Patient insurance coverage not verified for discharge destination",
        "auto_detect_keywords": ["eligibility not verified", "coverage not confirmed",
                                  "insurance verification pending"],
    },
    "snf_bed_not_secured": {
        "label": "SNF Bed Not Secured",
        "category": "placement",
        "default_sla_hours": 48,
        "description": "Skilled nursing facility placement not yet confirmed",
        "auto_detect_keywords": ["SNF bed not available", "SNF placement pending", "no SNF bed",
                                  "SNF not confirmed", "awaiting SNF placement"],
    },
    "irf_referral_pending": {
        "label": "IRF Referral Pending",
        "category": "placement",
        "default_sla_hours": 48,
        "description": "Inpatient rehabilitation facility referral not yet completed",
        "auto_detect_keywords": ["IRF referral", "rehab facility pending", "inpatient rehab referral"],
    },
    "home_health_agency_not_assigned": {
        "label": "Home Health Agency Not Assigned",
        "category": "placement",
        "default_sla_hours": 24,
        "description": "Home health agency not yet selected or notified",
        "auto_detect_keywords": ["home health agency not", "HHA not assigned", "home health not arranged"],
    },
    "followup_appt_not_scheduled": {
        "label": "Follow-up Appointment Not Scheduled",
        "category": "placement",
        "default_sla_hours": 24,
        "description": "Post-discharge physician follow-up appointment not yet booked",
        "auto_detect_keywords": ["follow-up not scheduled", "follow up appointment pending",
                                  "PCP appointment needed", "specialist appointment not scheduled"],
    },
    "transport_not_arranged": {
        "label": "Discharge Transport Not Arranged",
        "category": "social",
        "default_sla_hours": 24,
        "description": "Transportation to discharge destination not yet arranged",
        "auto_detect_keywords": ["transport not arranged", "transportation pending",
                                  "no transportation", "ride not arranged", "ambulance not booked"],
    },
    "caregiver_not_identified": {
        "label": "Caregiver Not Identified",
        "category": "social",
        "default_sla_hours": 48,
        "description": "No identified caregiver for home discharge",
        "auto_detect_keywords": ["no caregiver", "caregiver not identified", "caregiver unavailable",
                                  "lives alone", "no support at home"],
    },
    "home_safety_eval_pending": {
        "label": "Home Safety Evaluation Pending",
        "category": "social",
        "default_sla_hours": 48,
        "description": "Home safety assessment not yet completed",
        "auto_detect_keywords": ["home safety eval", "home assessment pending",
                                  "home modification needed"],
    },
    "social_work_consult_needed": {
        "label": "Social Work Consult Needed",
        "category": "social",
        "default_sla_hours": 24,
        "description": "Social work consultation not yet completed",
        "auto_detect_keywords": ["social work consult", "social worker needed",
                                  "SW consult pending", "case management consult"],
    },
    "medi_cal_eligibility_issue": {
        "label": "Medi-Cal Eligibility Issue",
        "category": "authorization",
        "default_sla_hours": 48,
        "description": "Medi-Cal coverage gap or eligibility issue identified",
        "auto_detect_keywords": ["Medi-Cal eligibility", "Medi-Cal coverage issue",
                                  "Medi-Cal not active", "Medi-Cal lapse"],
    },
    "calaim_care_mgmt_pending": {
        "label": "CalAIM Care Management Not Initiated",
        "category": "authorization",
        "default_sla_hours": 72,
        "description": "CalAIM Enhanced Care Management referral not yet submitted",
        "auto_detect_keywords": ["CalAIM", "Enhanced Care Management", "ECM referral",
                                  "Community Supports referral"],
    },
    "livanta_notice_not_issued": {
        "label": "Livanta QIO Notice Not Issued",
        "category": "clinical",
        "default_sla_hours": 2,
        "description": "Required Livanta QIO Important Message about hospital discharge rights not given",
        "auto_detect_keywords": ["Livanta notice", "QIO notice", "discharge rights notice",
                                  "Important Message not issued", "IM notice pending"],
    },
    "discharge_summary_not_completed": {
        "label": "Discharge Summary Not Completed",
        "category": "documentation",
        "default_sla_hours": 8,
        "description": "Physician discharge summary not yet signed",
        "auto_detect_keywords": ["discharge summary not completed", "summary pending",
                                  "physician summary not signed"],
    },
    "patient_education_not_completed": {
        "label": "Patient Education Not Completed",
        "category": "documentation",
        "default_sla_hours": 12,
        "description": "Discharge patient education/teaching not yet documented as completed",
        "auto_detect_keywords": ["patient education not completed", "teaching not done",
                                  "patient teaching pending", "education not documented"],
    },
    "custom": {
        "label": "Custom Barrier",
        "category": "other",
        "default_sla_hours": 24,
        "description": "Manually added barrier not matching a predefined type",
        "auto_detect_keywords": [],
    },
}

BARRIER_CATEGORIES = {
    "clinical":      {"label": "Clinical Readiness",       "color": "red"},
    "authorization": {"label": "Authorization & Insurance", "color": "amber"},
    "placement":     {"label": "Placement & Referrals",     "color": "orange"},
    "social":        {"label": "Social & Support",          "color": "blue"},
    "documentation": {"label": "Documentation",             "color": "purple"},
    "other":         {"label": "Other",                     "color": "gray"},
}
